Model Parameters:
  Mask:
    shift: 999.
  EdgeConv:
    convparams:
    - K: 16
      channels:
      - 64
      - 64
      - 64
    - K: 16
      channels:
      - 128
      - 128
      - 128
    - K: 16
      channels:
      - 256
      - 256
      - 256
    pooling: average
    BN: true
    activation: relu
  FinalPool:
    pooling: average
  
  ConvHead:
    params:
    - units: 256
      activation: relu
      drop_rate: 0.1
    - units: 128
      activation: relu
      drop_rate: 0.1
    - units: 64
      activation: relu
      drop_rate: 0.1
  num_classes: 2
 